site_name: Docs

repo_url: https://github.com/tyler55427/test
repo_name: tyler55427/test

theme:
    logo: https://thdlrt.oss-cn-beijing.aliyuncs.com/android-chrome-512x512.png
    name: 'material'
    icon:
      repo: fontawesome/brands/github
    features:
      - content.code.select
      - navigation.tabs
      - search.suggest
      - search.share
      - navigation.top
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

nav:
  - Home: index.md
  - 文档:
    - 01_文档/index.md
    - 学术:
      - 代码:
        - 代码基础: 01_文档/01_学术/01_代码/01_代码基础/C/00_base.md
        - 数据结构与算法: 01_文档/01_学术/01_代码/02_数据结构与算法/00_base.md
        - 算法题: 01_文档/01_学术/01_代码/03_算法题/00_base.md
      - 基础课程: 01_文档/01_学术/02_基础课程/00_base.md
      - 选修课程: 01_文档/01_学术/03_选修课程/00_base.md
      - 计算机课程: 01_文档/01_学术/04_计算机课程/00_base.md
    - 实用: 01_文档/02_实用/index.md
    - 工具类: 01_文档/03_工具类/index.md
    - 生活: 01_文档/04_生活/index.md
  - 如何做:
    - 02_如何做/index.md
    - 大学: 02_如何做/大学.md
    - 科研: 02_如何做/科研.md
    - 项目: 02_如何做/project.md
    - 待办: 02_如何做/todo_list.md
  - 产品:
    - 03_产品/index.md
  - 工具:
    - 04_工具/index.md
    - 学习: 04_工具/学习.md
    - 快捷键: 04_工具/快捷键.md
    - 电脑好用软件: 04_工具/电脑好用软件.md
    - 电脑开源工具: 04_工具/电脑开源工具.md
    - 电脑设置: 04_工具/电脑设置.md
    - 规范标准: 04_工具/规范标准.md
    - 问题经验教训: 04_工具/问题经验教训.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
