site_name: Docs

repo_url: https://github.com/tyler55427/test
repo_name: tyler55427/test

theme:
    logo: https://thdlrt.oss-cn-beijing.aliyuncs.com/android-chrome-512x512.png
    name: 'material'
    icon:
      repo: fontawesome/brands/github
    features:
      - content.code.select
      - navigation.tabs
      - search.suggest
      - search.share
      - navigation.top
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

nav:
  - index.md
  - 01_文档:
    - 01_学术:
      - 01_代码:
        - 01_代码基础:
          - C: 01_文档/01_学术/01_代码/01_代码基础/C/00_base.md
          - C++: 01_文档/01_学术/01_代码/01_代码基础/Cpp/00_cpp.md
          - Java: 01_文档/01_学术/01_代码/01_代码基础/Java/00_base.md
          - Python: 01_文档/01_学术/01_代码/01_代码基础/Python/笔记/python.md
        - 02_数据结构与算法:
          - 01_链表: 01_文档/01_学术/01_代码/02_数据结构与算法/01_链表/双向链表.md
          - 02_树: 01_文档/01_学术/01_代码/02_数据结构与算法/02_树/00_base.md
          - 03_散列哈希: 01_文档/01_学术/01_代码/02_数据结构与算法/03_散列哈希/00_base.md
          - 04_图: 01_文档/01_学术/01_代码/02_数据结构与算法/04_图/00_base.md
          - 05_串: 01_文档/01_学术/01_代码/02_数据结构与算法/05_串/KMP.md
          - 11_堆栈队列: 01_文档/01_学术/01_代码/02_数据结构与算法/11_堆栈队列/heap.md
          - 12_并查集: 01_文档/01_学术/01_代码/02_数据结构与算法/12_并查集/集合.md
          - 13_排序: 01_文档/01_学术/01_代码/02_数据结构与算法/13_排序/排序.md
        - 03_算法题:
          - 01_数组: 01_文档/01_学术/01_代码/03_算法题/01_数组/1-dim/荷兰国旗问题.md
          - 02_链表: 01_文档/01_学术/01_代码/03_算法题/02_链表/反转链表.md
          - 03_堆栈队列: 01_文档/01_学术/01_代码/03_算法题/03_堆栈队列/滑动窗口最大值.md
          - 04_树: 01_文档/01_学术/01_代码/03_算法题/04_树/翻转二叉树.md
          - 05_图: 01_文档/01_学术/01_代码/03_算法题/05_图/岛屿数量.md
          - 06_串: 01_文档/01_学术/01_代码/03_算法题/06_串/1-string/最长回文子串.md
          - 11_递归迭代: 01_文档/01_学术/01_代码/03_算法题/11_递归迭代/记忆化递归.md
          - 12_动态规划: 01_文档/01_学术/01_代码/03_算法题/12_动态规划/买卖股票.md
          - 13_模拟: 01_文档/01_学术/01_代码/03_算法题/13_模拟/数独.md
          - 14_搜索: 01_文档/01_学术/01_代码/03_算法题/14_搜索/二分/二分搜索.md
          - 15_贪心: 01_文档/01_学术/01_代码/03_算法题/15_贪心/跳跃游戏.md
          - 16_哈希: 01_文档/01_学术/01_代码/03_算法题/16_哈希/前缀和哈希.md
          - 17_位运算: 01_文档/01_学术/01_代码/03_算法题/17_位运算/只出现一次的数字.md
          - 18_数学: 01_文档/01_学术/01_代码/03_算法题/18_数学/质数.md
      - 02_基础课程:
        - 01_高等数学: 01_文档/01_学术/02_基础课程/01_高等数学/01_函数与极限.md
        - 02_线性代数: 01_文档/01_学术/02_基础课程/02_线性代数/01_线性方程组与矩阵.md
        - 03_概率统计: 01_文档/01_学术/02_基础课程/03_概率统计/01_事件与概率.md
      - 03_选修课程:
        - 01_数学分析: 01_文档/01_学术/03_选修课程/01_数学分析/00_base.md
        - 02_复变函数: 01_文档/01_学术/03_选修课程/02_复变函数/01_复数基本概念.md
        - 03_信号与系统: 01_文档/01_学术/03_选修课程/03_信号与系统/01_信号与系统.md
        - 04_数值计算方法: 01_文档/01_学术/03_选修课程/04_数值计算方法/01_绪论.md
        - 05_离散数学: 01_文档/01_学术/03_选修课程/05_离散数学/01_命题逻辑.md
        - 06_机器人原理: 01_文档/01_学术/03_选修课程/06_机器人原理/01_绪论.md
        - 07_贝叶斯: 01_文档/01_学术/03_选修课程/07_贝叶斯/01_贝叶斯分析简介.md
      - 04_计算机课程:
        - 01_计算机组成原理: 01_文档/01_学术/04_计算机课程/01_计算机组成原理/01_计算机基础.md
        - 02_操作系统: 01_文档/01_学术/04_计算机课程/02_操作系统/01_概述.md
        - 03_计算机网络: 01_文档/01_学术/04_计算机课程/03_计算机网络/01_计算机网络缩写.md
        - 04_数据库: 01_文档/01_学术/04_计算机课程/04_数据库/01_数据库概述.md
        - 05_编译原理: 01_文档/01_学术/04_计算机课程/05_编译原理/00_base.md
    - 02_实用:
      - API调用: 01_文档/02_实用/api_call.md
      - 命令行: 01_文档/02_实用/command.md
      - CUDA: 01_文档/02_实用/cuda.md
      - PPT制作: 01_文档/02_实用/ppt制作.md
      - 代理: 01_文档/02_实用/proxy.md
      - Python导入: 01_文档/02_实用/python_import.md
      - 软件: 01_文档/02_实用/software.md
      - WSL: 01_文档/02_实用/wsl.md
    - 03_工具类:
      - Claude: 01_文档/03_工具类/claude.md
      - Conda: 01_文档/03_工具类/conda.md
      - Docker: 01_文档/03_工具类/docker.md
      - Git: 01_文档/03_工具类/git/00_base.md
      - LaTeX: 01_文档/03_工具类/latex.md
      - Markdown: 01_文档/03_工具类/markdown.md
      - NPM: 01_文档/03_工具类/npm.md
      - Pip: 01_文档/03_工具类/pip.md
      - SSH: 01_文档/03_工具类/ssh.md
      - Vim: 01_文档/03_工具类/vim.md
    - 04_生活:
      - 吃饭: 01_文档/04_生活/吃饭.md
      - 工作: 01_文档/04_生活/工作.md
      - 银行卡: 01_文档/04_生活/银行卡.md
  - 02_如何做:
    - 大学: 02_如何做/大学.md
    - 科研: 02_如何做/科研.md
    - 项目: 02_如何做/project.md
    - 待办: 02_如何做/todo_list.md
  - 03_产品:
    - 应用: 03_产品/apps
    - 脚本: 03_产品/scripts
    - 技能: 03_产品/skills
  - 04_工具:
    - 学习: 04_工具/学习.md
    - 快捷键: 04_工具/快捷键.md
    - 电脑好用软件: 04_工具/电脑好用软件.md
    - 电脑开源工具: 04_工具/电脑开源工具.md
    - 电脑设置: 04_工具/电脑设置.md
    - 规范标准: 04_工具/规范标准.md
    - 问题经验教训: 04_工具/问题经验教训.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
